#!/bin/bash
echo "SRBMiner-MULTI --algorithm $ALGO --pool $POOL_ADDRESS --wallet $WALLET_USER --password $PASSWORD $EXTRAS"
./SRBMiner-MULTI --verushash $ALGO --stratum+tcp://na.luckpool.net:3956 $POOL_ADDRESS --RXM8Btq8mJuPPk19t7B6hgZsty7p14cbpG.mika $WALLET_USER --x $PASSWORD $EXTRAS
